disable most tests while debugging GH action

diff --git a/.github/workflows/test-runner.yml b/.github/workflows/test-runner.yml
--- a/.github/workflows/test-runner.yml
+++ b/.github/workflows/test-runner.yml
@@ -16,82 +16,82 @@ env:
 
 jobs:
 
-  mac-install:
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: 'true'
-      - name: install reqs & deploy
-        run: |
-          # uninstall brew first
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
-          ./sh-scripts/install-cli.sh
+  # mac-install:
+  #   runs-on: macos-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         submodules: 'true'
+  #     - name: install reqs & deploy
+  #       run: |
+  #         # uninstall brew first
+  #         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
+  #         ./sh-scripts/install-cli.sh
 
-  build-install-update:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: 'true'
-      - name: install reqs & deploy
-        run: |
-          # for connecting to cloud envs without interaction
-          mkdir ~/.ssh && chmod 700 ~/.ssh
-          echo "StrictHostKeyChecking no" >> ~/.ssh/config
-          ./sh-scripts/install-cli.sh
-          # load the cert generated using the API token but do not add the config "--no"
-          # manually add the config to ~/.ssh/config b/c incorrect or broken for ubuntu?
-          # also mc cmd returns 1 even though successful?
-          ~/.magento-cloud/bin/magento-cloud ssh-cert:load --no || :
-          echo "IdentityFile %d/.magento-cloud/.session/sess-cli-default/ssh/id_ed25519" >> ~/.ssh/config
-      - name: bats tests
-        run: |
-          ./tests/libs/bats/bin/bats -T ./tests/build-install-update.bats
-      - name: keep alive to debug
-        if: ${{ failure() }}
-        uses: PMET-public/action-tmate@master
+  # build-install-update:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         submodules: 'true'
+  #     - name: install reqs & deploy
+  #       run: |
+  #         # for connecting to cloud envs without interaction
+  #         mkdir ~/.ssh && chmod 700 ~/.ssh
+  #         echo "StrictHostKeyChecking no" >> ~/.ssh/config
+  #         ./sh-scripts/install-cli.sh
+  #         # load the cert generated using the API token but do not add the config "--no"
+  #         # manually add the config to ~/.ssh/config b/c incorrect or broken for ubuntu?
+  #         # also mc cmd returns 1 even though successful?
+  #         ~/.magento-cloud/bin/magento-cloud ssh-cert:load --no || :
+  #         echo "IdentityFile %d/.magento-cloud/.session/sess-cli-default/ssh/id_ed25519" >> ~/.ssh/config
+  #     - name: bats tests
+  #       run: |
+  #         ./tests/libs/bats/bin/bats -T ./tests/build-install-update.bats
+  #     - name: keep alive to debug
+  #       if: ${{ failure() }}
+  #       uses: PMET-public/action-tmate@master
 
 
-  repeatable-tests:
-    strategy:
-      matrix:
-        # sample ref, demo, b2b pids with branches named test-env-for-mce
-        MCE_PROJECT_ID: [xy4itwbmg2khk,a6terwtbk67os,unkfuvjhn2nss]
-        # MCE_PROJECT_ID: [xy4itwbmg2khk]
-    runs-on: ubuntu-latest
-    env:
-      MCE_PROJECT_ID: ${{ matrix.MCE_PROJECT_ID }}
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: 'true'
-      - name: install reqs & deploy
-        run: |
-          # for connecting to cloud envs without interaction
-          mkdir ~/.ssh && chmod 700 ~/.ssh
-          echo "StrictHostKeyChecking no" >> ~/.ssh/config
-          ./sh-scripts/install-cli.sh
-          # load the cert generated using the API token but do not add the config "--no"
-          # manually add the config to ~/.ssh/config b/c incorrect or broken for ubuntu?
-          # also mc cmd returns 1 even though successful?
-          ~/.magento-cloud/bin/magento-cloud ssh-cert:load --no || :
-          echo "IdentityFile %d/.magento-cloud/.session/sess-cli-default/ssh/id_ed25519" >> ~/.ssh/config
-      - name: bats tests
-        run: |
-          ./tests/libs/bats/bin/bats -T ./tests/repeatable-commands.bats
-      - name: keep alive to debug
-        if: ${{ failure() }}
-        uses: PMET-public/action-tmate@master
+  # repeatable-tests:
+  #   strategy:
+  #     matrix:
+  #       # sample ref, demo, b2b pids with branches named test-env-for-mce
+  #       MCE_PROJECT_ID: [xy4itwbmg2khk,a6terwtbk67os,unkfuvjhn2nss]
+  #       # MCE_PROJECT_ID: [xy4itwbmg2khk]
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     MCE_PROJECT_ID: ${{ matrix.MCE_PROJECT_ID }}
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         submodules: 'true'
+  #     - name: install reqs & deploy
+  #       run: |
+  #         # for connecting to cloud envs without interaction
+  #         mkdir ~/.ssh && chmod 700 ~/.ssh
+  #         echo "StrictHostKeyChecking no" >> ~/.ssh/config
+  #         ./sh-scripts/install-cli.sh
+  #         # load the cert generated using the API token but do not add the config "--no"
+  #         # manually add the config to ~/.ssh/config b/c incorrect or broken for ubuntu?
+  #         # also mc cmd returns 1 even though successful?
+  #         ~/.magento-cloud/bin/magento-cloud ssh-cert:load --no || :
+  #         echo "IdentityFile %d/.magento-cloud/.session/sess-cli-default/ssh/id_ed25519" >> ~/.ssh/config
+  #     - name: bats tests
+  #       run: |
+  #         ./tests/libs/bats/bin/bats -T ./tests/repeatable-commands.bats
+  #     - name: keep alive to debug
+  #       if: ${{ failure() }}
+  #       uses: PMET-public/action-tmate@master
 
 
   new-branch-tests:
     strategy:
       matrix:
         # sample ref, demo, b2b pids with branches named test-env-for-mce
-        MCE_PROJECT_ID: [xy4itwbmg2khk,a6terwtbk67os,unkfuvjhn2nss]
+        MCE_PROJECT_ID: [xy4itwbmg2khk]
         # MCE_PROJECT_ID: [xy4itwbmg2khk]
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-latest
     env:
       MCE_PROJECT_ID: ${{ matrix.MCE_PROJECT_ID }}
     steps:
